/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package EmpApp;

/**
 *
 * @author 750465
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    //MyHashTable employees = new MyHashTable(2);
    
    public NewJFrame() {
        
        initComponents();
        empOptionsPane.setVisible(true);
        addEmployeePanel.setVisible(false);
        empTypePane.setVisible(false);
        searchEmployeePanel.setVisible(false);
        
      /*  if (addEmployeePanel.setVisible(true)){
           searchEmployeePanel.setVisible(false);
        }
        else if (searchEmployeePanel.setVisible(true)){
            addEmployeePanel.setVisible(false);
        }
*/ 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titlePanel = new javax.swing.JPanel();
        titleText = new javax.swing.JLabel();
        empViewAll = new javax.swing.JButton();
        empRemove = new javax.swing.JButton();
        empEdit = new javax.swing.JButton();
        empSave = new javax.swing.JButton();
        empLoad = new javax.swing.JButton();
        empExit = new javax.swing.JButton();
        pteAdd = new javax.swing.JButton();
        empSearch = new javax.swing.JButton();
        empOptionsPane = new javax.swing.JLayeredPane();
        searchEmployeePanel = new javax.swing.JPanel();
        empNumSearchText = new javax.swing.JLabel();
        empResultsTextField = new javax.swing.JLabel();
        empDisplayResults = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addEmployeePanel = new javax.swing.JPanel();
        empNum = new javax.swing.JLabel();
        empNumTextField = new javax.swing.JTextField();
        empFN = new javax.swing.JLabel();
        empFNTextField = new javax.swing.JTextField();
        empLN = new javax.swing.JLabel();
        empLNTextField = new javax.swing.JTextField();
        empG = new javax.swing.JLabel();
        empGTextField = new javax.swing.JTextField();
        empWL = new javax.swing.JLabel();
        empWLTextField = new javax.swing.JTextField();
        empDR = new javax.swing.JLabel();
        empDRTextField = new javax.swing.JTextField();
        empType = new javax.swing.JComboBox();
        empTypeTextField = new javax.swing.JLabel();
        empTypePane = new javax.swing.JLayeredPane();
        empPTEParam = new javax.swing.JPanel();
        empHW = new javax.swing.JLabel();
        empHWTextField = new javax.swing.JTextField();
        empHPW = new javax.swing.JLabel();
        empHPWTextField = new javax.swing.JTextField();
        empWPY = new javax.swing.JLabel();
        empWPYTextField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        empFTEParam = new javax.swing.JPanel();
        empYS = new javax.swing.JLabel();
        empYSTextField = new javax.swing.JTextField();
        addButtonFTE = new javax.swing.JButton();
        cancelButtonFTE = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titlePanel.setBackground(new java.awt.Color(51, 51, 51));

        titleText.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        titleText.setForeground(new java.awt.Color(255, 255, 255));
        titleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleText.setText("Employee Management System");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(titleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(381, 381, 381))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleText)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        empViewAll.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empViewAll.setText("View All Employees");
        empViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empViewAll(evt);
            }
        });

        empRemove.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empRemove.setText("Remove An Employee");
        empRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empRemove(evt);
            }
        });

        empEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empEdit.setText("Edit An Employee's Information ");
        empEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empEdit(evt);
            }
        });

        empSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empSave.setText("Save");
        empSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSave(evt);
            }
        });

        empLoad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empLoad.setText("Load");
        empLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLoad(evt);
            }
        });

        empExit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empExit.setText("Exit");
        empExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empExitActionPerformed(evt);
            }
        });

        pteAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pteAdd.setText("Add Employee");
        pteAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empAdd(evt);
            }
        });

        empSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empSearch.setText("Search For An Employee");
        empSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empSearch(evt);
            }
        });

        empNumSearchText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empNumSearchText.setText("Enter Employee Number:");

        empResultsTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        empResultsTextField.setText("Search Results:");

        empDisplayResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empDisplayResultsActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout searchEmployeePanelLayout = new javax.swing.GroupLayout(searchEmployeePanel);
        searchEmployeePanel.setLayout(searchEmployeePanelLayout);
        searchEmployeePanelLayout.setHorizontalGroup(
            searchEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empNumSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empResultsTextField)
                    .addGroup(searchEmployeePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(searchEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empDisplayResults, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(224, Short.MAX_VALUE))
        );
        searchEmployeePanelLayout.setVerticalGroup(
            searchEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchEmployeePanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(empNumSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empDisplayResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(empResultsTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );

        addEmployeePanel.setBackground(new java.awt.Color(204, 204, 204));

        empNum.setText("Employee Number:");

        empFN.setText("First Name:");

        empLN.setText("Last Name:");

        empG.setText("Gender:");

        empWL.setText("Work Location:");

        empWLTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empWLTextFieldActionPerformed(evt);
            }
        });

        empDR.setText("Deduction Rate:");

        empType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Part Time Employee", "Full Time Employee" }));
        empType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empTypeCheck(evt);
            }
        });

        empTypeTextField.setText("Type of Employee:");

        empPTEParam.setBackground(new java.awt.Color(204, 204, 204));

        empHW.setText("Hourly Wage");

        empHPW.setText("Hours Per Week");

        empHPWTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empHPWTextFieldActionPerformed(evt);
            }
        });

        empWPY.setText("Weeks Per Year");

        cancelButton.setText("Cancel");

        addButton.setText("Add");

        javax.swing.GroupLayout empPTEParamLayout = new javax.swing.GroupLayout(empPTEParam);
        empPTEParam.setLayout(empPTEParamLayout);
        empPTEParamLayout.setHorizontalGroup(
            empPTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empPTEParamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(empPTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empWPYTextField)
                    .addComponent(empHWTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empHPWTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(empPTEParamLayout.createSequentialGroup()
                        .addGap(0, 348, Short.MAX_VALUE)
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, empPTEParamLayout.createSequentialGroup()
                        .addGroup(empPTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empHW)
                            .addComponent(empHPW)
                            .addComponent(empWPY))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        empPTEParamLayout.setVerticalGroup(
            empPTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empPTEParamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empHW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empHWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empHPW)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empHPWTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empWPY)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empWPYTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(empPTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        empFTEParam.setBackground(new java.awt.Color(204, 204, 204));

        empYS.setText("Yearly Salary");

        empYSTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empYSTextFieldActionPerformed(evt);
            }
        });

        addButtonFTE.setText("Add");
        addButtonFTE.setToolTipText("");
        addButtonFTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonFTEActionPerformed(evt);
            }
        });

        cancelButtonFTE.setText("Cancel");

        javax.swing.GroupLayout empFTEParamLayout = new javax.swing.GroupLayout(empFTEParam);
        empFTEParam.setLayout(empFTEParamLayout);
        empFTEParamLayout.setHorizontalGroup(
            empFTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empFTEParamLayout.createSequentialGroup()
                .addGroup(empFTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empFTEParamLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addButtonFTE, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButtonFTE))
                    .addGroup(empFTEParamLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(empFTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empYS)
                            .addComponent(empYSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        empFTEParamLayout.setVerticalGroup(
            empFTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empFTEParamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empYS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empYSTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 223, Short.MAX_VALUE)
                .addGroup(empFTEParamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButtonFTE)
                    .addComponent(cancelButtonFTE))
                .addContainerGap())
        );

        empTypePane.setLayer(empPTEParam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        empTypePane.setLayer(empFTEParam, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout empTypePaneLayout = new javax.swing.GroupLayout(empTypePane);
        empTypePane.setLayout(empTypePaneLayout);
        empTypePaneLayout.setHorizontalGroup(
            empTypePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(empFTEParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(empTypePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, empTypePaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(empPTEParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        empTypePaneLayout.setVerticalGroup(
            empTypePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empTypePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empFTEParam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(empTypePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(empTypePaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(empPTEParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
        addEmployeePanel.setLayout(addEmployeePanelLayout);
        addEmployeePanelLayout.setHorizontalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empNum)
                            .addComponent(empFN)
                            .addComponent(empLN)
                            .addComponent(empG)
                            .addComponent(empWL)
                            .addComponent(empDR)
                            .addComponent(empType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(216, 216, 216))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addEmployeePanelLayout.createSequentialGroup()
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(empWLTextField)
                            .addComponent(empNumTextField)
                            .addComponent(empFNTextField)
                            .addComponent(empLNTextField)
                            .addComponent(empGTextField)
                            .addComponent(empDRTextField))
                        .addContainerGap())
                    .addComponent(empTypePane)
                    .addGroup(addEmployeePanelLayout.createSequentialGroup()
                        .addComponent(empTypeTextField)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        addEmployeePanelLayout.setVerticalGroup(
            addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmployeePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empNumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empFN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empFNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empLN)
                .addGap(3, 3, 3)
                .addComponent(empLNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empGTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empWL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empWLTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empDR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(empDRTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(empTypeTextField)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(empType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(empTypePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        empOptionsPane.setLayer(searchEmployeePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        empOptionsPane.setLayer(addEmployeePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout empOptionsPaneLayout = new javax.swing.GroupLayout(empOptionsPane);
        empOptionsPane.setLayout(empOptionsPaneLayout);
        empOptionsPaneLayout.setHorizontalGroup(
            empOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empOptionsPaneLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(empOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(empOptionsPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(searchEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        empOptionsPaneLayout.setVerticalGroup(
            empOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(empOptionsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(empOptionsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(empOptionsPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(searchEmployeePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(empRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(empViewAll, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                            .addComponent(empEdit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empSave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empLoad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(empExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(empOptionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pteAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(empViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(empSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empLoad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(empExit)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(empOptionsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empViewAll(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empViewAll
        //employees.printTable();
    }//GEN-LAST:event_empViewAll

    private void empRemove(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empRemove
        // TODO add your handling code here:
    }//GEN-LAST:event_empRemove

    private void empEdit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empEdit
        // TODO add your handling code here:
    }//GEN-LAST:event_empEdit

    private void empSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSave
        // TODO add your handling code here:
    }//GEN-LAST:event_empSave

    private void empLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLoad
        // TODO add your handling code here:
    }//GEN-LAST:event_empLoad

    private void empSearch(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empSearch
       empOptionsPane.setVisible(true);
       addEmployeePanel.setVisible(false);
       searchEmployeePanel.setVisible(true);       
       
    }//GEN-LAST:event_empSearch

    private void empWLTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empWLTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empWLTextFieldActionPerformed

    private void empAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empAdd
       empOptionsPane.setVisible(true);
       searchEmployeePanel.setVisible(false);  
       addEmployeePanel.setVisible(true);
              
    }//GEN-LAST:event_empAdd

    private void empHPWTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empHPWTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empHPWTextFieldActionPerformed

    private void empTypeCheck(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empTypeCheck
        
        System.out.println(empType.getItemAt(empType.getSelectedIndex()));
              
        if (empType.getItemAt(empType.getSelectedIndex()) == "Part Time Employee")
        {
            empTypePane.setVisible(true);
            empFTEParam.setVisible(false);
            empPTEParam.setVisible(true);
            
        }
       
        if (empType.getItemAt(empType.getSelectedIndex()) == "Full Time Employee")
        {
            empTypePane.setVisible(true);
            empPTEParam.setVisible(false);
            empFTEParam.setVisible(true);
        }
        else if (empType.getItemAt(empType.getSelectedIndex()) == "...")
        {
            empTypePane.setVisible(false);
            
        }
    }//GEN-LAST:event_empTypeCheck

    private void empYSTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empYSTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empYSTextFieldActionPerformed

    private void addButtonFTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonFTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButtonFTEActionPerformed

    private void empExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empExitActionPerformed
        
    }//GEN-LAST:event_empExitActionPerformed

    private void empDisplayResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empDisplayResultsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empDisplayResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButtonFTE;
    private javax.swing.JPanel addEmployeePanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelButtonFTE;
    private javax.swing.JLabel empDR;
    private javax.swing.JTextField empDRTextField;
    private javax.swing.JTextField empDisplayResults;
    private javax.swing.JButton empEdit;
    private javax.swing.JButton empExit;
    private javax.swing.JLabel empFN;
    private javax.swing.JTextField empFNTextField;
    private javax.swing.JPanel empFTEParam;
    private javax.swing.JLabel empG;
    private javax.swing.JTextField empGTextField;
    private javax.swing.JLabel empHPW;
    private javax.swing.JTextField empHPWTextField;
    private javax.swing.JLabel empHW;
    private javax.swing.JTextField empHWTextField;
    private javax.swing.JLabel empLN;
    private javax.swing.JTextField empLNTextField;
    private javax.swing.JButton empLoad;
    private javax.swing.JLabel empNum;
    private javax.swing.JLabel empNumSearchText;
    private javax.swing.JTextField empNumTextField;
    private javax.swing.JLayeredPane empOptionsPane;
    private javax.swing.JPanel empPTEParam;
    private javax.swing.JButton empRemove;
    private javax.swing.JLabel empResultsTextField;
    private javax.swing.JButton empSave;
    private javax.swing.JButton empSearch;
    private javax.swing.JComboBox empType;
    private javax.swing.JLayeredPane empTypePane;
    private javax.swing.JLabel empTypeTextField;
    private javax.swing.JButton empViewAll;
    private javax.swing.JLabel empWL;
    private javax.swing.JTextField empWLTextField;
    private javax.swing.JLabel empWPY;
    private javax.swing.JTextField empWPYTextField;
    private javax.swing.JLabel empYS;
    private javax.swing.JTextField empYSTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton pteAdd;
    private javax.swing.JPanel searchEmployeePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
